### ISSUE TITLE
create production and development branches

### ISSUE THREAD

**Issue by pauldgifford** [vmc-field-team/bender#15]
properly use branches to ensure that issues are addressed in dev and inherited into production

rename master to development
create production 

refactor scripts for commits;
/data/dev/ : origin = development
/data/production : origin = production

reference:
https://www.w3docs.com/snippets/git/how-to-rename-git-local-and-remote-branches.html

**Comment by vmc-field-team** [comment]
- development has been correctly named from master to development
- dev-push.sh has been updated and tested

**Comment by pauldgifford** [comment]
promote.sh updated to use rynch instead of cp to exclude .git and .env

need to query last dev commit to use for production git push 
https://stackoverflow.com/questions/7293008/how-to-read-last-commit-comment

**Comment by pauldgifford** [comment]
Completed
prod-push.sh - commits to github in production branch
dev-push.sh - commits to github in development branch
promote.sh - updates /dev to /prod
