### ISSUE TITLE
Bender requiring org ID for Paid Pilot in Planning Stage

### ISSUE THREAD

**Issue by aosterholt** [vmc-field-team/bender#45]
Trying to add a new entry for a Paid Pilot and it is stopping me because it is requiring the org ID.  This is in the planning stage and no way to have an org ID at this point. Also, should we even require the orgID for a Paid Pilot? This is customer purchased so how would we get that if they do not grant us access. I could also see bad things down the road if bender automates deletion with Pilots. This workflow probably needs some updates. Screenshot posted to slack as I do not want to expose in public forum.

**Comment by crslen** [comment]
I think I fixed this.  It will ask you if you have an org id and if not it will move on to the next question.
