### ISSUE TITLE
Generating Consumption Plan PPT from Bender

### ISSUE THREAD

**Issue by nvibert** [vmc-field-team/bender#48]
The Sales team wants to create a Consumption Plan PPT and as Bender already stores the right information, it would be great if we could ask Bender to create it directly and store it on S3.
If a PPT is too complicated, then a PDF or a TextFile would be fine.

**Comment by crslen** [comment]
We have a mode report that was created for this - https://modeanalytics.com/vmware_inc/reports/1795dda2710a
CS should be using this for consumption data and will be working on bringing in data from saleforce to help complete the report.
